Update check.yaml

diff --git a/.github/workflows/check.yaml b/.github/workflows/check.yaml
--- a/.github/workflows/check.yaml
+++ b/.github/workflows/check.yaml
@@ -1,42 +1,21 @@
----
-name: Release Chart on S3 repo
+name: Sync office-js-api
 
-on:    
-  push:
-    branches:
-      - master
+on:
+  workflow_dispatch:
+  schedule: 
+    - cron: '*/5 * * * *'
 
-permissions:
-  # All other permissions are set to none
-  contents: write
-  # Technically read access while waiting for images should be more than enough. However,
-  # there is a bug in GitHub Actions/Packages and in case private repositories are used, you get a permission
-  # denied error when attempting to just pull private image, changing the token permission to write solves the
-  # issue. This is not dangerous, because if it is for "apache/airflow", only maintainers can push ci.yml
-  # changes. If it is for a fork, then the token is read-only anyway.
-  packages: write
 env:
-  GITHUB_REPOSITORY: ${{ github.repository }}
-  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  BRANCH_NAME: ${{ github.ref_name }}
   
 jobs:
-  build:
-    name: Chart release
+  sync:
+    name: "Sync"
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Create Release
-        id: create_release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
-        with:
-          tag_name: v1.0.0.1
-          release_name: Release ${{ github.ref }}
-          body: |
-            Changes in this Release
-            - First Change
-            - Second Change
-          draft: false
-          prerelease: false
+    - name: Master error handler
+      if: ( github.event_name == 'workflow_dispatch' && github.ref_name == 'master' )
+      run: echo "Can't run from master manualy" && exit 1
+
+    - name: Get branch
+      run: echo ${{ github.ref_name }}
