Update test-sctipts.yml

diff --git a/.github/workflows/test-sctipts.yml b/.github/workflows/test-sctipts.yml
--- a/.github/workflows/test-sctipts.yml
+++ b/.github/workflows/test-sctipts.yml
@@ -67,7 +67,10 @@ jobs:
       run: vagrant ssh -c "sudo wget https://download.onlyoffice.com/install/workspace-install.sh"
 
     - name: run script
-      run: vagrant ssh -c "echo 'FOO=2 ; if $FOO = 2 ; then exit 1 ; else exit 0 ; fi' >> script.sh ; bash ./script.sh ; echo $? " 
+      run: vagrant ssh -c "status=$? ; cmd='sudo echo 'N' | sudo bash workspace-install.sh --skiphardwarecheck true --makeswap false' "
+  
+    - name: run script
+      run: vagrant ssh -c "$cmd [ $status -eq 0 ] && echo 'Script end successfull' || echo 'Script install failed, check logs' "
       
     #vagrant ssh -c "sudo echo 'N' | sudo bash workspace-install.sh --skiphardwarecheck true --makeswap false ; if [ $? != 0 ] ; then exit 1; fi  "
      
